apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-config
data:
  MONGODB_HOST: "mongo-pedidos-service"
  MONGODB_DATABASE: "pedidosdb"
  MONGODB_PORT: "27017"
  GATEWAY_CLIENTES: "http://localhost:9090/v1/clientes"
  GATEWAY_PRODUTOS: "http://localhost:9090/v1/produtos"
  GATEWAY_PAGAMENTOS: "http://localhost:9090/v1/pagamentos"
