apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config
type: Opaque
stringData:
  MONGODB_HOST: "mongodb-hostname"
  MONGODB_DATABASE: "database-name"
  MONGODB_PORT: "27017"
  MONGODB_USERNAME: "mongodb-username"
  MONGODB_PASSWORD: "mongodb-password"
  GATEWAY_CLIENTES: "http://localhost:9090/v1/clientes"
  GATEWAY_PRODUTOS: "http://localhost:9090/v1/produtos"
  GATEWAY_PAGAMENTOS: "http://localhost:9090/v1/pagamentos"
