apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat3-ms-pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soat3-ms-pedidos
  template:
    metadata:
      labels:
        app: soat3-ms-pedidos
    spec:
      containers:
        - name: soat3-ms-pedidos
          image: franciscosviana/soat3-ms-pedidos:v1
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: pedidos-config
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pedidos-config
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pedidos-config
                  key: MONGODB_PORT
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: pedidos-config
                  key: MONGODB_DATABASE
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-pedidos-secret
                  key: mongo-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-pedidos-secret
                  key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: soat3-ms-pedidos-service
spec:
  type: NodePort
  selector:
    app: soat3-ms-pedidos
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 32005
